#!/usr/local/bin/php
<?php

error_reporting(0);

# config
$prefix = "/usr/local/webdata";
$ip = '192.168.0.178';
$svnsvr = "svn://{$ip}";
$username = 'mingxin.zhuang';
$password = '';
$auth = " --username $username --password $password ";

# parse
if (!isset($argv[1])) {
    echo "请输入需求号，如：STORY #88888::超返又来一个分流，哈哈！\n";
    exit(1);
}
$story = trim($argv[1]);

if (false !== strpos($story, '#')) {
    list($branches, $version) = explode('#', $story);
    $branches = trim(strtolower(str_replace('_', '', $branches)));
    $version = intval($version);
    # current dir => project name, like 'fun'、'mobile'
    $project_name = basename($_SERVER['PWD']);

    $des_path = "{$svnsvr}/{$project_name}/branches/{$branches}{$version}";
    $release = "{$svnsvr}/{$project_name}/release";

    system("svn list {$auth} {$des_path} 2>&1 |grep 'non-existent' 2>&1 >/dev/null", $list_return);

    # svn copy
    if (empty($list_return)) {
         # 分支不存在则建立新分支
        $copy_return = system("svn copy -r HEAD {$auth} {$release} {$des_path} -m \"{$story}\"  2>&1 >/dev/null");
        echo "～创建分支成功.\n";
    }
    else {
        echo "～分支已存在.\n";
    }

}
else if (is_numeric($story)) {
    $branches = 'story';
    $project_name = basename($_SERVER['PWD']);
    $version = intval($story);

    $des_path = "{$svnsvr}/{$project_name}/branches/{$branches}{$version}";
}

#switch
echo "开始switch到当前目录......";
system("svn sw {$auth} {$des_path} .  -r HEAD --ignore-ancestry 2>&1 >/dev/null", $list_return);
if ($list_return) {
    echo "分支switch失败，分支不存在！\n";
    exit(1);
}

echo "分支switch到当前目录成功！\n";

# 检查当前目录分支
echo "当前分支：" . system("svn info|grep URL") . "\n";

# 如果当前目录有Runtime目录，则删除

if (is_dir('./Runtime')) {
    system("rm -rf ./Runtime");
    echo "\n已删除runtime\n";
}
exit(0);

?>
